#!/bin/bash
echo "=== Prometheus Unbound Health Check ==="
echo ""
echo "--- Docker Services ---"
docker ps --format "table {{.Names}}\t{{.Status}}"
echo ""
echo "--- TimescaleDB Tables ---"
docker exec tsdb psql -U tsadmin -d prometheusdb -c "\dt"
echo ""
echo "--- Hypertables ---"
docker exec tsdb psql -U tsadmin -d prometheusdb -c "SELECT hypertable_name, num_chunks FROM timescaledb_information.hypertables;"
echo ""
echo "--- Row Counts ---"
docker exec tsdb psql -U tsadmin -d prometheusdb -c "SELECT 'metrics' as table, COUNT(*) FROM metrics UNION ALL SELECT 'anomalies', COUNT(*) FROM anomalies UNION ALL SELECT 'incidents', COUNT(*) FROM incidents UNION ALL SELECT 'ai_logs', COUNT(*) FROM ai_logs;"
